- csug/debug.stex
- csug/foreign.stex
- csug/io.stex
- csug/libraries.stex
- csug/objects.stex
- csug/syntax.stex
- csug/system.stex
- csug/use.stex
- release_notes/release_notes.stex
- s/enum.ss
- s/expeditor.ss
This fixes a variety of duplicated articles (``the the``) and the like.
> Fix typos involving articles.

- csug/Makefile
Since anyone can now "make docs" for csug, all hrefs to tspl4 should be absolute. Right now all of the tspl4 links on, for example, http://gwatt.github.io/csug/csug_1.html and http://cdn.virgil.xyz/csug9/csug_1.html 404. (Those are the index pages, but the same is true of the tspl4 links in the content—e.g., the first link on http://gwatt.github.io/csug/io.html.)
> Make hrefs to tspl4 absolute.

- s/pdhtml.ss
* Mark the files as HTML5 rather than HTML4.
* Use target attributes rather than onclick events to open links in specific windows.
* Add a missing table row element.
* Replace the deprecated name attribute with an id attribute (and replace the anchors with spans).
* Replace the deprecated valign attribute with a style attribute.
> Begin a refresh of the profiler's HTML output.

- makefiles/installsh
I wasn't able to get "make install" to work on my Ubuntu 15.10 system because of a minor error in the makefiles/installsh script.   Enclosed patch fixes the problem.
> Bash test(1) does not allow bare numbers with ==, so use -eq

- .gitignore
This commit adds the TAGS file generated by etags to the list of files ignored
by git.
> Ignore etags files

- configure
This changes the configure script from unconditionally assigning CPPFLAGS,
CFLAGS, and LDFLAGS to the empty string, to only assigning them to the empty
string if they are unset.
This allows one to set the flags before calling configure, rather than as parameters
explicitly passed to the configure script.
> Allow CPPFLAGS, CFLAGS, and LDFLAGS to be passed through configure

- LOG
- c/expeditor.c
- s/expeditor.ss
This works for Mac OS X.
On Linux, characters entered with Ctrl+Shift+U #### aren't decoded properly (it seems to zero one of the bytes?)  It might be a couple days before I can investigate, but I leave this here for review of the approach.
> Expeditor unicode support

- LOG
- s/syntax.ss
This commit fixes calls to syntax-error in case and exclusive-cond (s/syntax.ss) which had their arguments reversed causing exceptions like:
`Exception in syntax-error: #<syntax ((0))> is not a string`
Instead of:
`Exception: invalid case clause ((0))`
In cases such as:
`(case 0 ((0)))`
All tests pass on my machine, and there weren't any other obvious (ie static strings) cases of this.
> case and exclusive-cond syntax-error calls

- LOG
- examples/csocket.c
- examples/socket.ss
Change the foreign procedure definitions to use the more portable int
rather than integer-32.  Switch to a custom port
[make-custom-binary-input/output-port] rather than a generic port
[make-input/output-port], which resulted in deleting quite a bit of
code.  Fix various compiler warnings in the C code, and along the way,
fix a signedness bug in c_write that could have resulted in not writing
the full buffer (but reporting that it did) in the case of errors from
write.
examples/csocket.c, examples/socket.ss
> updated the sockets example to work with the current version of Chez.

- .gitattributes
Apparently Github detects .ms files as MAXscript, making the mats files look like they're not Scheme. It also thinks the .h files are C++ as opposed to C. This pull request simply adds a .gitattributes file to hint the correct languages to Github.
> Correcting language stats

- LOG
- s/pdhtml.ss
Check both the beginning file pointer (bfp) and end file pointer (efp)
of the source location associated with a profile counter when updating
its count.
Assuming that each expression has a unique bfp with respect to profiling
seems to give accurate execution counts for s-expression-based source
locations as in Scheme, but causes problems when targeting other kinds
of syntax. For instance, a C-style function call, referencing the called
function by name, such as "fn(arg)", can logically have profile counters
associated with 1) the function name reference ("fn") and 2) the entire
function call expression ("fn(arg)"), both of which begin at the same
source location. Only the bfp is checked when updating profile counters,
so the two source locations are conflated, and only one counter is …
> Fix profile counters for non-s-expression source

- LOG
- csug/objects.stex
- mats/record.ms
- s/5_1.ss
- s/newhash.ss
- s/primdata.ss
This patch adds `record-equal+hash` for getting or setting a
customization for `equal?` and `equal-hash` on an RTD to apply to its
instances.
Potential issues:
* The API explicitly uses a pair of functions, and the identity of the
pair is relevant for determining when the pair's `car` is used for
`equal?`. Any suggestions for a more tasteful data structure or API?
* Relatedly, although there's a check when a pair is provided that its
`car` and `cdr` have procedures, the pair could be mutated at any
time. The effect of mutation is not particularly specified.
* When using `record-equal+hash` to get an RTD's current mapping,
there's no way to distinguish an explicit mapping versus inheriting
and ancestor's mapping. The difference can matter if the ancestor's
mapping is changed (in which case …
> add record-equal+hash

- LOG
- mats/4.ms
- s/cp0.ss
- s/primdata.ss
I'm still not sure that this is an error, and I'm still not sure that this is the correct fix.  Anyway ... 
The result of
(begin (#3%map / '(5 4 3 2 1 0)) 'something)
is `'something`, but I expect to see an error in the last `(/ 0)`.
The problem is in the reduction for `#3%map` when it is called only for effects. The reduction test that the procedure is _pure_, but I think that it must be _ivory_. 
If this is correct, I can make the same changes for `for-each` because it has the same problem.
The PR is splitted in two commits, but I expect to squash them before they are merged.
> Fix reduction for map with optimization level 3

- LOG
- s/primdata.ss
The return value is marked as `fixnum`, but it should be `boolean`.
(I'm not sure if it is necesary to recalculate the bootfiles.)
> Fix fxbit-set? signature

- BUILDING
- LOG
- c/Mf-a6nt
- c/Mf-i3nt
- c/Mf-ta6nt
- c/Mf-ti3nt
- c/vs.bat
- configure
- mats/Mf-a6nt
- mats/Mf-base
- mats/Mf-i3nt
- mats/Mf-ta6nt
- mats/Mf-ti3nt
- mats/vs.bat
- s/Mf-base
- workarea
The future of Unix tools on Windows is likely Bash on Ubuntu on Windows (a.k.a "Bash/WSL"), so this patch adapts the configure script and makefiles to support it – at least for the latest version, where Windows executables can be run from Bash/WSL.
Just running `configure` should create a Linux build in Bash/WSL, but this patch makes `configure` set up a Windows build when the `OS` environment variable is set to `Windows_NT`.
Visual Studio is found and set up essentially as before, but backslashes in makefiles are treated differently in Cygwin and Bash/WSL, so some parts are moved to ".bat" files. The makefiles now use "cmd.exe" to launch batch files or otherwise switch to Windows-command world. Finally, Bash/WSL needs "scheme.exe" instead of just "scheme" to run the built executable.
> support Windows build on Bash/WSL

- LOG
- c/externs.h
- c/new-io.c
- c/prim5.c
- csug/objects.stex
- mats/bytevector.ms
- mats/root-experr-compile-0-f-f-f
- mats/root-experr-compile-2-f-f-f
- release_notes/release_notes.stex
- s/bytevector.ss
- s/primdata.ss
Not a high priority, but would be nice to have if it seems like a good idea: Expose zlib's compress() and uncompress() API as `bytevector-compress` and `bytevector-decompress`.
This is useful to Racket, because compiled code is written via `compile-to-port` to a bytevector. With this commit, the resulting bytevector can be compressed and decompressed without going through a file.
> add bytevector-compress and bytevector-decompress

- LOG
- mats/misc.ms
- s/cp0.ss
I'm not sure about this, and I'm not sure if this is the correct fix ...
If I run 
(expand/optimize 
'(if (zero? (random 37))
(pariah (display "green"))
(void)))
I get 
(if (#2%zero? (#2%random 37))
(#2%display "green")
(#2%void))
but I expect something like
(if (#2%zero? (#2%random 37))
(begin
(pariah (void))
(#2%display "green"))
(#2%void))
The problem is that `(pariah)` is marked as `simple?` and it's removed from the `begin` sequence.
This change breaks the reduction of
(expand/optimize 
'(if (zero? (random 37))
(pariah (void))
(void)))
> Don't mark pariah as `simple?`

- LOG
- mats/3.ms
- s/syntax.ss
Expanding to a definition means that it doesn't interrupt a definition
sequence.
> fix `(define-values () ....)` to expand to a definition

- LOG
- c/vs.bat
I've been trying to build and run Chez in a container so support for Visual Studio BuildTools would be nice.
I have not yet successfully used VS's BuildTools to produce a build that passes all the mats and I'd be happy to sit on this PR until I can prove it all works.
Current mat summary: https://gist.github.com/kleinpa/84f535942dc370846774e38bbf17328a
> Add support for building with Visual Studio BuildTools

- LOG
- configure
- wininstall/.gitignore
- wininstall/Makefile
- wininstall/bundle.wxs
- wininstall/locate-vcredist.bat
- wininstall/product.wxs
- wininstall/ui.wxs
- Separate 64 and 32 bit MSIs
- Add wix bundle to combine MSIs into single installer
- Use basic wix UI
- Use merge modules to install vcredist package
- Add script to locate vcredist merge modules
- Fix installer status text by adding WixUI_ErrorProgressText ref
Merge modules seems to be the preferred method for installing the redistributable package, which should decrease the package size and speed up installation. This commit also addresses a bug where the installer does not work when VC redistributable is not already installed.
The 32 and 64 bit components were split into separate MSIs because Windows Installer only officially supports packages containing a single architecture. A package bundle is then created containing both MSIs so only a single file needs to be distributed.
There …
> Refactor windows installers and fix vcredist

- csug/io.stex
The documentation currently shows
(format "~@:(~a~)" "Ouch!")  =>  "ouch!"
Chez 9.4.1 instead outputs "OUCH!"
Chez Scheme Version 9.4.1
Copyright 1984-2017 Cisco Systems, Inc.
> (format "~@:(~a~)" "Ouch!")
"OUCH!"
Chez 8.4 also yields this same behavior.
> small change in documentation, ouch to shout OUCH

- LOG
- s/cp0.ss
The first commit adds a checks that first argument of `map` is a procedure in cp02 expansion to raise the same error that the non expanded version
This fix an error in the tests in Windows of the mat "4.ms", [line 1082-1083](https://github.com/cisco/ChezScheme/blob/master/mats/4.ms#L1082-L1083) and [line 1713-L1714](https://github.com/cisco/ChezScheme/blob/master/mats/4.ms#L1713-L1714)
(error? ; nonprocedure
(map 3 '(a b c)))
;[...]
(error?
(for-each 3 '(a b c)))
The summary is something like
-------- o=0 cp0=t --------
[...]
270c273
< 4.mo:Expected error in mat map: "map: 3 is not a procedure".
---
> 4.mo:Expected error in mat map: "attempt to apply non-procedure 3".
340c343
< 4.mo:Expected error in mat for-each: "for-each: 3 is not a procedure".
---
> 4.mo:Expected error in mat …
> Check that first argument of map in cp02 expansion

- LOG
- mats/4.ms
- s/cp0.ss
When  `(#2%map p '())` is reduced in cp0 to `'()`, the expression of p is discarded without a check that it is a procedure. But the signature of `map` in primdata.ss is `((procedure list list...) ->(list))`.
The problem is that in the [PR of cptypes #192](https://github.com/cisco/ChezScheme/pull/192) uses the signature to mark `p` as a procedure after this expression, assuming that otherwise `map` would have raise an error. 
The code to show the problem should be a mix of some reductions of cp0 and some reduction of cptypes:
(define (f p b)
(unbox b)
(map p (if (box? b) '() '(1 2 3)))
(list p (procedure? p)))
(f 7 (box 0)) ;==> 
; ==> (7 #f) in the current version of Chez Scheme
; ==> [error] in Chez Schem + this patch
; ==> (7 #t) in Chez Scheme + cptypes [wrong]
I think that the best …
> Remove special case for (#2%map p '()) in cp0

- LOG
- mats/8.ms
- release_notes/release_notes.stex
- s/syntax.ss
The [CSUG entry](http://cisco.github.io/ChezScheme/csug9.5/libraries.html#./libraries:s17) for  standalone `export` forms permits an export-spec to take the form `(import import-spec ...)`, yet the implementation currently seems to require `(import import-spec)`.
```
> (library (Z) (export) (import (scheme)) (export (import)))
Exception: invalid export spec (import)
Type (debug) to enter the debugger.
> (library (A) (export a) (import (scheme)) (define a 1))
> (library (B) (export b) (import (scheme)) (define b 2))
> (library (C) (export) (import (scheme)) (export (import (A) (B))))
Exception: invalid export spec (import (A) (B))
Type (debug) to enter the debugger.
```
This commit tries to make the implementation consistent with CSUG on this point, but could use review by someone with …
> standalone export form now handles (import import-spec ...)

- LOG
- c/prim.c
- csug/smgmt.stex
- mats/7.ms
- release_notes/release_notes.stex
- s/7.ss
- s/primdata.ss
This patch exposes the internal thread rezdezvous for GC to applications through a `collect-rendezvous` function.
For many purposes, `collect-rendezvous` is a variant of `collect` that works when multiple threads are active. More precisely, while `collect` actually collects, the `collect-rendezvous` function invokes the collect-request handler (in an unspecified thread).
> add `collect-rendezvous`

- LOG
- c/globals.h
- c/scheme.c
- mats/7.ms
- release_notes/release_notes.stex
- s/7.ss
- s/primdata.ss
This aims to fix the issue with compiled library code in (non-base) boot files that is described in #69.
> handle compiled library code in boot files once base boot is loaded

- csug/numeric.stex
were reversed in csug, flipped to be correct.
> Return descriptions for most-positive-fixnum and most-negative-fixnum

- makefiles/Mf-install.in
As `${LibBin}` is expanded to `${TempRoot}${InstallLibBin}`, if we create a symlink with a source pointing to the `${TempRoot}` path, once installed (for example in an RPM), the symlink will still point to the `${TempRoot}` path.
That's why we must use the final path `${InstallLibBin}`. Another solution could have been to use a relative path.
> Symbolic links must be created for the install path and not the temp root path

- LOG
- mats/foreign.ms
- mats/foreign4.c
- s/x86_64.ss
This is a repair for the main bug report in #320.
I have not yet run the updated tests on ppc32le, but I'll do that tomorrow.
> x86_64: fix foreign-procedure `&` results that are not a multiple of a word

- .vscode/settings.json
- LOG
- c/version.h
- configure
now you can build Chez Scheme like this:
```
./configure --installprefix=$HOME/scheme --disable-x11
make
make install
```
see help by `./configure --help`
> add an option `--disable-x11` to configure, which allows you to build Chez Scheme with X11 disabled

- LOG
- mats/misc.ms
- s/cp0.ss
A macro or compiler can generally give a name to the procedure result of a `lambda` form by wrapping it in `(let ([<name> _]) <name>)`. Currently, though, that local name can get replaced by a different name from the context. For example, in
(define g (let ([f (lambda (x) x)]) f))
the procedure bound to `g` probably has the name "g", although it depends on whether cp0 is enabled.
In this example, the name "g" ends up being used because `letify` effectively throws away the `let` wrapper and has no way to communicate the discarded name to its context. Although using the outer name could be considered a feature, I think it's probably an intentional consequence of the transformation.
This PR adjusts cp0 so that it doesn't replace a procedure name when one has been given already, and that has …
> prefer nearest binding name for procedures

- LOG
- mats/misc.ms
- mats/patch-compile-0-f-t-f
Some tests need repair for different evaluation modes – such as `interpret` instead of `compiled`, which doesn't preserve names.
> update tests for "prefer closest binding name"

- LOG
- c/scheme.c
- csug/foreign.stex
- csug/system.stex
- mats/7.ms
- s/7.ss
- s/mkheader.ss
- s/primdata.ss
The main change in this patch adds `load-compiled-from-port`, which roughly complements `compile-to-port`. Racket-on-Chez uses `compile-to-port` to turn a set of "linklets" for a module into a set of object-code fragments; it now uses `load-compiled-from-port` to run those fragments. (Previously, Racket-on-Chez relied on `fasl-read` and a rough imitation of the internals of `do-load-binary`.)
A second change is related, although distinct from `load-compiled-from-port`: `Sregister_boot_file_fd` gives a custom Chez Scheme startup the ability to load a boot file from a place that is not directly identifiable as a path, such as the middle of an executable file – especially when using the implicit EOF at the end of a compressed stream. After booting, a custom executable can use …
> add `load-compiled-from-port`

- LOG
- configure
This will close #325 
The main issue is that on current OS X, X11 is no more provided default.
> Autoconfig, detect if X11 exist on Mac OS X

- LOG
- csug/system.stex
- mats/misc.ms
- release_notes/release_notes.stex
- s/cmacros.ss
- s/compile.ss
- s/cpnanopass.ss
- s/inspect.ss
- s/patch.ss
- s/primdata.ss
- s/prims.ss
Procedure source locations are useful for error backtraces at a much lower cost (while losing some precision) compared to keeping full inspector information.
This patch adds `generate-procedure-source-information`, which defaults to #f and only applies when `generate-inspector-information` is #f. If `generate-procedure-source-information` is #t, then a source location is preserved with a code object even when  `generate-inspector-information` is #f.
> keeping procedure srclocs without other inspector info

- LOG
- mats/8.ms
- s/compile.ss
- s/syntax.ss
Should we revise the flush-output-port change to fetch parameter values once per `(when ...)`?
I left a WIP commit at the tip hoping that @akeep can sanity check it.
Here is the error message issue (note that it is masked by the WIP commit):
```
> (import-notify #t)
> (generate-wpo-files #t)
> (compile-imported-libraries #t)
> (with-output-to-file "B.ss"
(lambda ()
(pretty-print
'(library (B) (export b) (import (scheme)) (define b 9))))
'replace)
> (with-output-to-file "prog.ss"
(lambda ()
(for-each pretty-print
`((import (B) (scheme))
(import-notify #t)
(define (run args)
(guard (c [#t (display-condition c) (newline)])
(pretty-print
(top-level-value (car args) (environment (cdr args))))))
(when (> b 0) ;; reference export
(let ([args (map string->symbol (command-line-arguments))])
(if (= …
```
> clarify "unknown module" error message; flush expand-output and expand/optimize-output

- LOG
- c/segment.c
When using the USE_MALLOC allocator instead of USE_MMAP, valgrind gives warnings. The merge request silences the warnings. Maybe better to initialize the relevant fields explicitly instead of zeroing the whole segment.
==16544== Conditional jump or move depends on uninitialised value(s)
==16544==    at 0x11E308: copy (in /home/chn/chez/install/bin/scheme)
==16544==    by 0x126BCD: S_gc_oce (in /home/chn/chez/install/bin/scheme)
==16544==    by 0x114A81: Scompact_heap (in /home/chn/chez/install/bin/scheme)
==16544==    by 0x13AAD7: Sbuild_heap (in /home/chn/chez/install/bin/scheme)
==16544==    by 0x10F9D9: main (in /home/chn/chez/install/bin/scheme)
==16544==  Uninitialised value was created by a heap allocation
==16544==    at 0x483577F: malloc (vg_replace_malloc.c:299)
==16544==    by …
> Avoid reading undefined values by zero-initializing allocation

- LOG
- mats/cp0.ms
- mats/patch-compile-0-f-t-f
- mats/patch-compile-0-t-f-f
- mats/patch-interpret-0-f-f-f
- mats/patch-interpret-0-f-t-f
- mats/root-experr-compile-0-f-f-f
- release_notes/release_notes.stex
- s/cp0.ss
Sketch of a fix for #389 
Is there any point in trying `#2%apply` in `fold-primref2` when `app-convention` is not `call`? Seems that if `objs-if-constant` succeeds here, but the `apply` handler didn't turn `apply` into `call`, then we're going to end up residualizing anyway, so I'm inclined to check the convention earlier in that first `cond` clause and simplify.
> heed app-convention to fix apply issue

- LOG
- mats/foreign.ms
- mats/foreign2.c
- s/cpnanopass.ss
A repair for #379
The `dofretu...*` intrinsics use ac1 without declaring it as killed, which effectively broke register allocation for handling string/bytevector foreign-call results or callable arguments.
There was a "FIXME" in the implementation of `dofretu...*` that suggests avoiding ac1, so maybe that intent is why ac1 never got declared. With respect to the "FIXME", though, `get-room` does preserve td and ts, but I didn't find a way to avoid ac1 on x86 (because `alloc` involve ts and xp?). So, that's why the repair declares ac1 as killed by `dofretu...*` instead of trying to avoid it.
> fix string allocation for foreign-callable argument or foreign-call return

- LOG
- bintar/Makefile
- makefiles/Mf-install.in
- s/.gitattributes
- s/Mf-base
- s/update-revision
- wininstall/a6nt.wxs
- wininstall/i3nt.wxs
- wininstall/ta6nt.wxs
- wininstall/ti3nt.wxs
This pull request aims to help answer support questions like:
1. what source did I build in this particular workarea?
1. what source was used to build this installed binary?
My original stab at this exposed a `#%$scheme-revision` that we could get at via the repl. That was convenient at run time, but the extra rounds of bootstrapping made that approach irritating at compile time.
I've since scaled back to the much simpler approach of recording minimal revision-control information in a `revision` file alongside the boot files. This seems to work well enough for my use cases.
The `update-revision` script could be extended for folks who mirror the git source in some other revision control system. The git attributes on `update-revision` insert the appropriate revision if folks export the …
> record revision control information alongside boot files

- LOG
- bintar/Makefile
- makefiles/Mf-install.in
- mats/8.ms
- s/.gitattributes
- s/Mf-base
- s/syntax.ss
- s/update-revision
- wininstall/a6nt.wxs
- wininstall/i3nt.wxs
- wininstall/ta6nt.wxs
- wininstall/ti3nt.wxs
The expander currently treats an interleaved init expression `e` as if it were `(define <fresh> e)`.
cp0 often cleans up cases where an interleaved init returns something other than a single value:
```
> (print-gensym #f)
> (define program
'(top-level-program
(import (scheme))
(printf "Hello\n")
(define (f) (display "world\n") (values 4 5 6))
(f)))
> (eval program)
Hello
world
> (parameterize ([run-cp0 (lambda (f x) x)])
(eval program))
Hello
world
Exception: returned three values to a single value return context
```
It doesn't help if we change the call `(f)` to `(begin (f) (void))`, since the expander may treat `begin` as a splicing form:
```
> (parameterize ([print-gensym #f])
(expand
'(top-level-program
(import (scheme))
(printf "Hello\n")
(define (f) (display "world\n") (values 4 5 …
```
> ignore multiple-value return from interleaved init expressions

- LOG
- mats/record.ms
- s/cp0.ss
In expressions like
(record-ref ... (begin (newline) (record ...)))
the current reduction was dropping the possible side effect expressions
in this case the `(newline)`.
A complete example is
(run-cp0 (lambda (cp0 x) (cp0 (cp0 (cp0 x))))]) ; three times
(let ()
(define-record mybox (val))
(mybox-val (begin (display 1) (make-mybox 2))))
==> `2` instead of `12`
---
As a side note, running only two times the cp0 pass, it is not enough to reduce some expressions like `(mybox-val (make-mybox 2)))`. It is necessary to run cp0 three times. I don't know after expansions and inlining if this kind of pattern is common. I tried compiling with three times cp0 instead of two and the compilation time changes very little. Perhaps it could be useful to change the default.
> Fix record-ref reduction in cp0

- LOG
- s/x86.ss
Building the compiler in safe mode for 32-bit x86 reveals incorrect uses of `fxzero?` in "x86.ss": a 32-bit immediate is not necessarily a fixnum.
For example, compilation of "newhash.ss" triggers an error, since it involves an `fx+` on 523658599 which turns into an inline `+` on the immediate 2094634396.
The misuses of `fxzero?` cause no trouble when compiled as unsafe, since that turns into a `eq?` that works as intended in this case.
> fix uses of `fxzero?` on a 32-bit immediate in 32-bit mode

- LOG
- s/primdata.ss
They were defined inside a block with the `proc` flag, but they are `enum-set`s.
This confuses `cp0`. For example
(enum-set? #3%$file-options) ; ==> #t
(procedure? #3%$file-options) ; ==> #t (but should be #f)
(run-cp0 (lambda (cp0 x) x)) ; disable cp0
(procedure? #3%$file-options) ; ==> #f
> Fix signatures of $file-options and friends

- LOG
- mats/5_2.ms
Make two small fixes in `relop-length` for the mirrored case.
Also, in the test replace `(and ...)`  with `(list ...)`, so they detect any discrepancy.
---
Note: While debugging, I tried to test this in scheme.exe adding a few `(display <something>)` here and there. But I couldn't see any change in the output. Do I have to turn on some parameter like `likely-to-be-compiled`?
> Small fix in relop-length

- BUILDING
- LOG
- c/vs.bat
- wininstall/locate-vcredist.bat
I've made the appropriate changes to support building chez with VS2019. The only problem I encountered when building is that Redistributable MSMs isn't included with any of the default workloads anymore as it's being deprecated. So, I added a note to the windows section of the building document that it needs to be installed.
> Added support for building chez with VS2019.

- LOG
- mats/io.ms
- release_notes/release_notes.stex
- s/cpnanopass.ss
The string-length-in-chars calculation in `$make-textual-input-port` needed updating for immutable strings in case an immutable string is passed to `open-string-input-port`.
> fix `open-string-input-port` on immutable strings

- LOG
- c/prim5.c
- csug/system.stex
- release_notes/release_notes.stex
Signed-off-by: Alexander Shopov <ash@kambanaria.org>
> Use setenv rather than putenv on non WIN32 environments

- LOG
- c/scheme.c
p is a pointer that iterates over path, which is buffer.
We should not try to get to an address preceding its start
Since there was an execution path that leads to that
guard against this with an additional check.
Signed-off-by: Alexander Shopov <ash@kambanaria.org>
> Add additional check to prevent going before start of buffer

- LOG
- mats/foreign.ms
- release_notes/release_notes.stex
- s/x86_64.ss
Floating-point registers used for arguments and results were not preserved while activating or deactivating a thread for a `__collect_safe` foreign call or callable.
> fix __collect_safe on x86_64 for floating point args/results

- LOG
- s/compile.ss
The `(close-port op)` in the `finish-compile` called by `compile-whole-program` and friends appears to have been dropped during the recent reorganization.
I don't have a simple test program, but changing this fixed some issues for me in the Swish mats (some are still broken since we relied on concatenating .so files).
Edit: updated branch to use the new-fangled with-object-file. Seemed to work for me.
> close port in compile-whole-program and compile-whole-library

- LOG
- c/scheme.c
gcc 9.1.0 fails to compile with -Werror and -O3 because it detects that `n` might be used uninitialize in line
`if (n != scheme_version) {`
We do know that `n` will be initialized in `if (zget_uptr(file, &n) != 0) {` but gcc doesn't know that unless compiled with LTO.
> Initialize n to 0

- c/gc.c
It looks like the WIPECLEAN code got out of date. Not sure if my attempted fix is on target.
> fix typo in WIPECLEAN

- c/fasl.c
The warning was introduced in commit 88501743.
> Fix warning in fasl.c

- LOG
- mats/3.ms
- s/cpnanopass.ss
In `np-push-mrvs`'s `Mvcall`, the continuation `k` wasn't used in the case for alloc, inline, and foreign-call expressions, so the result of a `call-with-values` form could get lost in a non-tail position. In the example below, the result of `(thing-pos posx)` gets lost.
```
;; cp0 is needed to expose `record-ref`:
(run-cp0 (lambda (cp0 x)
(let ([r (cp0 x)])
r)))
(define miscompiled
(lambda (bx)
(define-record-type thing
(fields pos)
(nongenerative #{thing hlg584lmg5htbdauw7dkid2sh-0}))
(set-box! bx (make-thing 'x))
(let ([posx (unbox bx)])
(cons 'result
(call-with-values
(lambda ()
(if (thing? posx)
;; compiled as inline load:
(thing-pos posx)
(do-something-else)))
list)))))
;; Should print`(result x)`
(printf "~s\n" (miscompiled (box #f)))
```
> fix missing continuation call in `cp-push-mvrs`

- LOG
- csug/system.stex
- csug/use.stex
- mats/7.ms
- mats/root-experr-compile-0-f-f-f
- mats/root-experr-compile-2-f-f-f
- release_notes/release_notes.stex
- s/compile.ss
- s/primdata.ss
In previous versions of Chez Scheme, multiple object files could be
combined by concatinating them into a single file.  To support faster
object file loading and loadability verification, recompile information
and information about libraries and top-level programs within an object
file is now placed at the top of the file.  The new
concatenate-object-files procedure can be used to combine multiple object
files while moving this information to the top of the combined file.
> Add concatenate-object-files procedure.

- c/schsig.c
Commit 72d90e4c67849908da900d0b6249a1dedb5f8c7f ("library-manager, numeric, and bytevector-compres
improvements") introduced a regression causing Win32 nmake builds to
fail due to an undefined symbol in c\schsig.c.
This symbol (scheme_signals_registered) is defined in a preprocessor-
conditional code block excluding WIN32 between lines 544 and 737.
This commit bypasses the build regression by enclosing the unresolved
expression in a preprocessor conditional excluding WIN32.
See GitHub Issue #497 for more details:
https://github.com/cisco/ChezScheme/issues/497
> Exclude unresolved symbol scheme_signals_registered on Win32 builds

- LOG
- s/primdata.ss
The result of `fasl-read` may be `#f`.
Example from @mflatt :
(let-values ([(o get) (open-bytevector-output-port)])
(fasl-write #f o)
(if (fasl-read (open-bytevector-input-port (get)))
'wrong
'correct))
> Fix fasl-read signature

- LOG
- c/Mf-a6nt
- c/Mf-i3nt
- c/Mf-ta6nt
- c/Mf-ti3nt
- mats/Mf-a6nt
- mats/Mf-i3nt
- mats/Mf-ta6nt
- mats/Mf-ti3nt
When MSYS2 bash sees the command "cmd.exe /c make.bat" it will
silently convert the /c into c:\, as it translates unixy paths
to Windows paths. This can be disabled by setting the environment
variable MSYS2_ARG_CONV_EXCL to *. So do that for this particular
command. It will be harmless in other environments like Cygwin.
> Fix makefile for MSYS2

- LOG
- c/expeditor.c
Distributions that use musl libc, such as Alpine, doesn't define
`__GLIBC__` yet still doesn't have xlocale.h.
> Fix build on Linux with musl libc

- LOG
- c/schlib.c
- mats/foreign.ms
- mats/foreign2.c
- s/cpnanopass.ss
This patch is a follow-up to #364 and commit 4cd942be6a, where `(%tc-ref cp)` was supposed to be preserved by moving it into `%cp` — but intrinisics used for bytevector argument types like `u8*` can kill `%cp`. This commit uses a temporary to expose things properly to the register allocator.
> fix foreign-callable handling of bytevector arguments

- LOG
- c/segment.c
- c/windows.c
When handling paths, Windows is case-insensitive, but unices are case-sensitive.
This simple patch facilitates cross-compiling the Windows version on a Unix system, and doesn't affect at all the native, Windows compilation.
To be more explicit, on a Linux system with an appropriate cross-compiler installed,
```
./configure -m=ta6nt --threads --toolprefix=x86_64-w64-mingw32-
./workarea ta6nt
make -C ta6nt/c -f Mf-ta6nt cross=t o=o
```
will fail with:
```
segment.c:92:10: fatal error: WinBase.h: No such file or directory
92 | #include <WinBase.h>
|          ^~~~~~~~~~~
compilation terminated.
```
(and another similar error in windows.c) unless this present patch is applied.
> Change includes <Win[bB]ase.h> => <winbase.h>

- LOG
- c/externs.h
- c/foreign.c
- c/windows.c
> Small refactoring and proper unicode handling of error messages.

- LOG
- mats/3.ms
- s/cpnanopass.ss
- s/np-languages.ss
When the wrong number of values are returned to a multiple-value context, the stack pointer is left as-is while calling the exception handler. The intent is to keep the current procedure's frame in place for debugging. However, there's no guarantee that the return address is still on the stack (much less in a return register, when there is one); for example, the continuation starting with the current frame may have been captured and just restored. If the return address is not in place, then the current continuation is ill-formed in the exception handler.
For example, this program tends to crash:
```
(define (go)
(call-with-values get
(lambda (a b) (list a b))))
;; returns just one value after capturing the continuation:
(define (get)
(call/cc
(lambda (k)
(collect) ; do something …
```
> continuation repair for return-arity error

- LOG
- s/arm32.ss
Changes in #530 created (exposed?) problems with the arm32 implementation of return-address label references. 
Currently, building arm32le boot files gets stuck. The problem is with the "funky12" encoding of immediates in A32, where a load of a larger immediate value can end up fitting in a smaller instruction encoding. The backwards references for return-arity errors get large enough that this matters: as code gets further away due to various label calculations, the return-address instructions can get shorter, pulling the code closer together again, and that push-and-pull effect can prevent the label-address assignment from terminating. The encoding problem might not have been a problem prior to #530, where return-address label references were always forward references, but I'm not sure. …
> make arm32 return-address encoding size montonic w.r.t. offset

- NOTICE
Commit 8858b34bd92ac8d2b6511dc9ca17ebfa06a1bd93 ("Add LZ4 support and
use it by default for compressing files") added LZ4 support and the
lz4 submodule, but did not update the NOTICE file, unlike zlib support
is handled.
> NOTICE: Mention LZ4

- LOG
- s/cpnanopass.ss
Add a special case in cpnanopass.ss for `(eq? (ftype-pointer-address x) 0)`. 
`eqv?`, `equal?` already have the same special case.
> Add special case in cpnanopass for (eq? (ftype-pointer-address x) 0)

- LOG
- c/expeditor.c
- c/externs.h
- c/prim5.c
- c/scheme.c
- c/stats.c
The time.h header is required to make the timespec struct available for
the prototypes.
Fixes: https://github.com/cisco/ChezScheme/issues/281
> Fix missing include in externs.h

- LOG
- mats/primvars.ms
- s/primdata.ss
Fix signature of `generate-temporaries`. The argument can be a list, a syntax with a list or an annotation.
> Fix signature of generate-temporaries

- BUILDING
- csug/foreign.stex
Adds information on building docs to `BUILDING`; updates docs on ftype pointer types in `foreign-procedure` to be more precise (as inspired by #557).
> Doc updates

- LOG
- c/number.c
- mats/5_3.ms
- release_notes/release_notes.stex
When a negative bignum is shifted right by a multiple of the bigit bit size (which is 32), when a shifted-off bit is non-0, and when the result would be a sequence of bigits with all 1 bits before rounding to deal with the dropped bits, a carry that should have been delivered to a new high bigit was dropped.
Old behavior:
```
> (bitwise-arithmetic-shift (- 307 (expt 16 240)) -32)
0
```
Corrected behavior:
```
> (bitwise-arithmetic-shift (- 307 (expt 16 240)) -32)
-2269007733883335972287082669296112915239349672942191252221331572442536403137824056312817862695551072066953619064625508194663368599769448406663254670871573830845597595897613333042429214224697474472410882236254024057110212260250671521235807709272244389361641091086035023229622419456
```
This bug was discovered by @samth and …
> repair bignum shift right

- LOG
- csug/foreign.stex
The user guide mention an outdated DLL which does not necessarily exist in recent installments of Windows 10. [According to Wikipedia](https://en.wikipedia.org/wiki/Microsoft_Windows_library_files#MSVCRT.DLL,_MSVCP*.DLL_and_CRTDLL.DLL), `MSVCRT.DLL` exists since Windows 95, and I tested on a Windows XP VM that it does exist in that (unsupported) Windows version.
> Mention an up-to-date DLL for Windows

- LOG
- mats/Mf-a6le
- mats/Mf-a6osx
- mats/Mf-ta6le
- mats/Mf-ta6osx
- release_notes/release_notes.stex
- s/x86_64.ss
For x86_64, it seems that integer values passed in registers should be sign-extended to at least 32 bits. In the case that a foreign-call argument is passed via `(& integer-8)` or `(& integer-16)` — which no one is likely to do in practice! — the sign extension didn't happen.
Clang on macOS apparently only takes advantage of the sign extension when compiling with optimization, but  "foreign1.mo" is compiled without optimization, so the existing test didn't find the problem. This patch changes the "s/Mf-..." files for x86_64 macOS and Linux to include `-O2` when compiling, but a more consistent change probably would be better. (For the Racket branch of Chez Scheme, the makefiles have been revised so that flags used for compiling the kernel are also used to compile `foreign1.mo`, and that's …
> x86_64: fix corner case of foreign calls for signed 8-bit or 16-bit integers with &

- BUILDING
- mats/Mf-base
- clean now removes "output" (in addition to output-*)
- the default target ("report") now properly creates "output" instead
of erroring becaues it doesn't exist
- repair functionality of root-experr and patches targets.  They now
will find the errors-* files in any of the output* directories
- add root-experrs target for convenience
The root-expert* and patch-* files regenerated by the root-experr and patches targets don't show up as outgoing changes, since regenerating them breaks the symlink from the work area to the git controlled file.  It was like that before I made any changes to the makefile, though.
> bug fixes in mats/Mf-base

- LOG
- s/bytevector.ss
This fixes misnamed pattern variables in bytevector-*-ref. It appears to be a cut & paste bug since before open-sourcing.
Practically, this has no effect as the affected code is avoided by `unaligned-integers` which appears to be `#t` for all currently supported platforms.  Flipping `unaligned-integers` to `#f` appears to emit the proper code, but there are other compile errors down the chain.  There may be a larger issue here of whether `unaligned-integers` should be supported option.
> fix misnamed pattern variables in bytevector-*-ref

- LOG
- c/Mf-base
- mats/Mf-arm32le
- mats/Mf-base
These updates support cross-compiling arm32le and fix an issue with `make -j 8 partialx` for recent GNU Make.
* Escape `$(MAKE)` to fix parallel mat issue observed with GNU Make 4.2.1:
"make[1]: warning: jobserver unavailable: using -j1."
mats/Mf-base
* Export some Mf-config variables and include Mf-config in mats to support
arm32le cross-compilation
c/Mf-base, mats/Mf-arm32le, mats/Mf-base
``` sh
$ sudo apt install binutils-arm-linux-gnueabihf gcc-arm-linux-gnueabihf
```
``` sh
$ sudo dpkg --add-architecture armhf
$ sudo vi /etc/apt/sources.list
```
Add the following lines to /etc/apt/sources.list:
```
deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ focal main restricted
deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ focal-updates main restricted
deb [arch=armhf] …
```
> makefile updates

- release_notes/release_notes.stex
Commit 0d5ec1da7 broke the release notes, so a fix is needed in order to generate the docs.
> Fix the release notes so `make docs` succeed

- LOG
- c/new-io.c
- c/scheme.c
- c/version.h
From the description in S_bytevector_read in c/new-io.c:
/* If we are running on Apple Silicon under Rosetta 2 translation, work around
a bug (present in 11.3.1 at least) in its handling of memory page protection
bits.  One of the tasks that Rosetta handles is to appropriately twiddle the
execute and write bits based on what's happinging to the memory in order to
preserve the illusion that the pages have RWX permissions, whereas Apple
Silicon enforces a W^X (write XOR execute) model.  For some reason, this
bit-twiddling sometimes fails when the bytevector passed to `read` extends
onto a page that's currently R-X, causing the `read` to fail with EFAULT
("bad address").  By writing to each subsequent page, we force Rosetta to
do the right magic to the protection bits.  (Or at least it makes …
> add workaround for Rosetta 2 bug in [t]a6osx builds

- s/np-languages.ss
L4.5 has several terminals that it does not use. Later languages,
however, do use them. So I moved the introduction site for those
terminals to the languages where they are first used.
> Move unused terminals in L4.5 to later languages.

- LOG
- mats/format.ms
- mats/root-experr-compile-0-f-f-f
- mats/root-experr-compile-2-f-f-f
- release_notes/release_notes.stex
- s/format.ss
`(lambda () (printf "~a~:*"))`
> Fix bug in printf with certain control strings and argument counts

- .github/workflows/test.yml
Always run the archive/upload workspace steps (even if previous
steps failed or timed out).
Set an explicit timeout for the "Run tests" step.  (Avoid waiting
for the default job-wide 6 hour timeout if the tests hang.)
> github workflow update

- LOG
- mats/5_1.ms
- release_notes/release_notes.stex
- s/5_3.ss
The result of
(rational-valued? +inf.0+0.0i)
is `#t` but it should be `#f`.
> Fix rational-valued? for numbers with an exceptional real part

- LOG
- mats/5_3.ms
- release_notes/release_notes.stex
- s/5_3.ss
makes <=, =, and >= transitive as required by R6RS by changing behavior
of mixed exact/inexact comparisons in the range where fixnums have
greater precision than flonums.  For example, the flonum representation
of 9007199254740992.0 and 9007199254740993.0 is identical,
but obviously the fixnums 9007199254740992 and 9007199254740993
are not.  In order for = and the inclusive inequalities to be transitive,
exact/inexact comparisons must behave as if the inexact number was replaced by
its exact representative.  A similar change was made for the strict
inequalities as well (even though they were already transitive).
Fixes #606
> fix exact/inexact comparisons where fixnum->flonum had loss of precision

- LOG
- mats/misc.ms
- mats/thread-check.ss
- mats/thread.ms
Consolidate the $thread-check code to bring the version in misc.ms up to date with the thread.ms changes from 0a6a1e14e7ecb9e39fa7a10a8584ed2fec24cbf4.
I noticed the code had gotten out of sync while investigating a spurious failure of $thread-check in misc.ms mat cost-center clause 45.
> consolidate $thread-check testing code

- LOG
- c/arm32le.c
This fixes compilation on musl libc which presently does not implement
these sysconf constants [\[0\]][0]. Please note though that this only fixes
compilation, there is still a separate run-time issue (see #622).
[0]: https://www.openwall.com/lists/musl/2017/07/24/1
> arm32le: only use cache sysconf constants if they are defined

- BUILDING
- LOG
- configure
- makefiles/Makefile.in
The `configure` flags `--installdoc`, `--installcsug`, and `--installreleasenotes` control the installation location.
The commits https://github.com/racket/ChezScheme/commit/b75700b4a205a75d4c5f5128fbeb01a27eaaae6f (a.k.a. https://github.com/racket/racket/commit/a9dd06917cbdb3a14ac3572fb89bff061c9d6324) and https://github.com/racket/racket/commit/d897379ef64178347ba7af3f0314317433d00410 added this same interface to Racket's variant of Chez Scheme.
I have not changed `make install` to also install the documentation because it seems useful for `make install` to continue to work in environments without a TeX installation.
> add `make install-docs`

- LOG
- release_notes/release_notes.stex
- s/cpnanopass.ss
- s/ppc32.ss
- s/primdata.ss
Three commits for small repairs backported from the Racket branch:
* repair ppc32 code generation when a branch displacement is exactly 32,764 bytes
* repair register handling — in a way that matters only for x86 — for a foreign callable float argument
* repair too-narrow signatures for `multibyte->string` and `string->multibyte`
The commits don't include new tests. It must be possible to construct an expression that would try a 32,764-byte branch on ppc32, but it's not obvious and doesn't seem worth the trouble; there was such a branch generated by a Racket library at the time of the repair. For x86, existing tests could already fail and would sometimes fail in the Racket CI setup (but I don't know how to probe for x87 stack misuse more directly). For the signature changes, I think …
> small repairs for old platforms

- LOG
- csug/foreign.stex
Consolidation of #647, #648, and #649 + a `LOG` entry.
- `Slocked_objectp` is now named correctly, as opposed to the previous incorrect `Sunlocked_objectp`.
- Correctly marked `Sforeign_callable_{entry_point,code_object}` as macros, rather than functions.
- Correctly marked `Ssymbol_to_string` as a function, rather than a macro.
> Fix foreign docs in several places

- BUILDING
If a space is used as the doc instructed, `configure` gives error "option '--installprefix' unrecognized or missing an argument"
> --installprefix requires an equal sign

- LOG
- mats/fx.ms
- s/cpnanopass.ss
In 102b2c1082, the auto-generated case in `np-place-overflow-and-trap` for `raw` was not the correct treatment of the form.
> repair for overflow checking and `raw` form

- LOG
- c/gc.c
- mats/4.ms
This is a backport of https://github.com/racket/ChezScheme/commit/e2cb8363a491692c55ef5739033ed94ec7c0de02.
When sweeping weak pairs and the max target generation is greater than the minimum target generation, then an updated car may need to be marked as dirty.
> repair for weak pairs and `collect` target generations

- LOG
- c/gc.c
- mats/4.ms
- release_notes/release_notes.stex
When an ephemeron pair refers to an object in younger generation, and when a collection would move that object to a generation that's less the maximum target generation, the collector could sometimes mishandle the ephemeron pair by trying to register it multiple times for later handling.
> repair collector handling of ephemerons

- LOG
- s/syntax.ss
Plain `_` patterns in `syntax-case` occurs fairly frequently in code (more than 80 occurrences in Chez Scheme itself), and these patterns never fail. There are used like `else` clauses for `syntax-case`.
An easy optimization is to avoid calling `$syntax-dispatch` for such patterns and directly embed the `()` return value that would result for such a call. A similar optimization already existed for patterns that consists of a single identifier.
With that optimization, `cp0` can easily optimize out the last call to `syntax-error` that is never reached.
Before:
```
> (expand/optimize '(syntax-case x () (_ 'ok)))
(let ([tmp x])
(let ([tmp (#3%$syntax-dispatch tmp '_)])
(if tmp 'ok (#3%syntax-error tmp))))
```
After:
```
(expand/optimize '(syntax-case x () (_ 'ok)))
(begin x 'ok)
```
---- …
> Optimize _ pattern in syntax-case clauses

- mats/4.ms
In attempting to improve some tests, commit a4654e4ee lost two adjustments to `collect-maximum-generation` to ensure that tests work when the parameter is set to 1 (as in some modes that are tried by `make test-more`).
> repair tests for cmg=1

- c/fasl.c
- configure
Commit 360d5ef952 missed an adjustment for big-endian machines — partly due to the bad way that a swap was implemented, where it did not use a suitable macro to find the right offset.
Also, fix `configure` for detecting `ppc32osx`.
> repair pb loading for big-endian architectures

- build.bat
Make the Windows build script `build.bat` more like `configure` by updating Git submodules unless an `/as-is` flag is provided.
> add Git submodule update to `build.bat`

- .github/workflows/build.sh
- .github/workflows/ci.yml
- .github/workflows/test.sh
Mostly reverts 01b5bb60cc, but also ~~changes "/c" to "//c"~~ uses `MSYS_NO_PATHCONV=1` --- which seems to be the right repair to the original problem based on the way Windows `bash` variants treat arguments that start with `/`.
> restore simpler Windows CI

- BUILDING
There is a small typo in the document, where existing is misspelled as exsisting.
> Update BUILDING -- fixed small typo

- s/build.zuo
Changes in the "unicode" directory were not tracked correctly. The missing dependency affects rebuilding via pb, for example.
> fix dependencies for cross compilation

- mats/hash.ms
- s/newhash.ss
- s/primdata.ss
Provide a way to work around the 10.x breaking change in `hashtable-cells`.
> add $hashtable-cells that skips immutable check

- mats/8.ms
- release_notes/release_notes.stex
- s/syntax.ss
Calling `library-exports` on a compiled library raises an exception if the library has not yet been imported.
If we compile testfile-li3.ss and start a new session, we get:
```
> (load-library "testfile-li3.so")
> (library-exports '(testfile-li3))
Exception in library-exports: unexpected binding (global . #{testfile-li3 dxvp567u7nmy7h0a66skcx-272})
Type (debug) to enter the debugger.
```
With the change on this branch, if we recompile testfile-li3.ss and start a new session, we get: 
```
> (load-library "testfile-li3.so")
> (library-exports '(testfile-li3))
(x)
```
Is this approach misguided? If not, maybe we can tidy up and cherry-pick the next time we have a compelling reason to rebuild the boot files. (Right now it's mingled with the changes for #310.)
The original `chi-top-library` …
> library-exports raises an exception for compiled library that is not yet imported

- c/build.zuo
- c/externs.h
- c/scheme.c
- c/self-exe.c
- csug/use.stex
- release_notes/release_notes.stex
Support portable boot files (`%x`) on more platforms
> Support portable boot files on more platforms

- c/externs.h
- c/foreign.c
- c/windows.c
- csug/foreign.stex
- mats/foreign.ms
_Am I late to the Chez Scheme 10 party?_
This is an old PR that's now reworked. Basically, an non-documented feature of `load-shared-object` is that it accepts `#f`. On UNIX it does something useful, but on Windows it just makes an invalid memory reference. 
The behavior on UNIX systems is to make the exported symbols of the executable as well as all shared objects linked to it available as foreign entries (what essentially `dlopen(NULL, ...)` does). It's very useful to get standard C library functions in a portable way; moreover, when creating a custom executable based on Chez Scheme, all dynamic libraries linked to the executable are readily available with `(load-shared-object #f)` to have access to the linked foreign entries. It helps decoupling the shared objects from their paths.
> Make (load-shared-object #f) portable

- c/externs.h
- c/gc-011.c
- c/gc-ocd.c
- c/gc-oce.c
- c/gc-par.c
- c/gc.c
- c/thread.c
- configure
The first commit is based on a suggestion from @owaddell. It changes `configure` to infer threaded or non-threaded C flags when a machine type is supplied. It also adjusts `configure` in smaller ways to avoid mismatches between specified and inferred configurations related to threading.
The second commit skips useless compilation of `gc-par.c` for non-threaded builds. This is done via the C preprocessor, instead of the makefile level, due to the way a non-threaded pb build may use a threaded host's configuration for compiling the kernel as a bootstrapping path.
The third commit fixes a bug related to `S_make_mutex` for tpb, especially on a 32-bit platform such as Wasm via Emscripten.
> refine kernel compilation for threading modes

- c/prim5.c
- mats/unix.ms
The `system` primitive is intended to be like a `__collect_safe` foreign call, allowing other threads to perform a collection while waiting for the shell command to return. Its shell-command argument is allocated, however, so `system` needs a copy of its argument while its thread is deactivated.
> repair for `system` in thread that can be deactivated

- c/self-exe.c
Commit ff97b9003aa065c4ac2b1bf09f4876ec654ece9b introduces "self-exe.c" using C99-and-later forms, which were not previously used in Chez Scheme. But it also uses `strdup` and `strtok_r`, which are widely available but not C99. Those functions turn out not to be available on some old environments that are still relevant to Racket, for example.
It always seems dumb to write yet another alternative to `strdup` and `strtok`, but the trade-off here seems worthwhile to me.
> avoid some C functions that are not in C99

- c/prim5.c
- mats/unix.ms
Fixes a mistake in d7cc2cf2e5. This mistake was noticed by some C compilers, but I missed the warnings.
> unbreak `system` in a thread that has interrupts disabled

- boot/pb/equates.h
- c/scheme.c
- c/stats.c
- s/default.def
- s/machine.zuo
- s/tunix.def
- s/unix.def
Trying to pick `time-t-bits` is a problem, particularly for i3le, since some 32-bit Linux variants now use a 64-bit `time_t`. Fortunately, the only use of `time-t-bits` is in the kernel to select between `Sinteger64` and `Sinteger32`, and just using `Sinteger64` is safe.
> remove time-t-bits from machine definition

- mats/misc.ms
A `compute-size-increments` test has been a long-time problem. It turns out that it was failing randomly due to a random list of symbols stashed in a thread parameter by an earlier test; sometimes, one of those symbols can reach a lot of data. The solution here is to not count data reachable from thread parameters.
A `cost-center-time` test has been failing on very slow machines. As a timing test, it's inherently unreliable, but turning up the limit should make failures rare enough without making the test useless.
> improve some tests that have been unreliable

- BUILDING
- c/types.h
- c/version.h
- configure
Update `configure` to infer a suitable machine based on "$MSYSTEM", and clear out some misleading WSL/Cygwin names and comments. Also, adjust the setjmp/longjmp configuration to work for pb in a CLANGARM64 environment.
> improve configure and build when using MSYS2

- s/cpnanopass.ss
This simplifies tracing programs whose output is expected to conform to some known format by using a separate port for logs. It also helps to preserve expected log ordering when other layers (e.g. Racket's expander) also log messages that should be displayed in the order they occurred.
> Send nanopass tracer logs to error port

- IMPLEMENTATION.md
- c/segment.c
- s/arm32.ss
- s/arm64.ss
- s/cpprim.ss
- s/ppc32.ss
- s/riscv64.ss
- s/x86.ss
- s/x86_64.ss
Corrected some typos,
Changed many tabs to 4-whitespaces,
Reformatted some backend code.
Some changes might be unnecessary. Take them as you see fit.
> Correct typos and reformat code

- csug/syntax.stex
- mats/8.ms
- mats/root-experr-compile-0-f-f-f
- release_notes/release_notes.stex
- s/primdata.ss
- s/syntax.ss
This contribution adds the `quote-syntax` form to the language. This form, which can also be found in Racket and Guile, is like `syntax` but does not substitute pattern variables.  (In fact, `quote-syntax` is like the `syntax` form from the R<sup>4</sup>RS appendix.)
The `quote-syntax` can be helpful for macro writers when the quoted datum's contents are not controlled by the macro and unwanted capture of pattern variables has to be avoided.
> Syntax quoting

- release_notes/release_notes.stex
The release notes mentioned a change to the treatment of exact 0 as a divisor, but not as a dividend. The release notes now also point out that this change is not consistent with R6RS.
> update release notes on `/` and exact `0`

- configure
- makefiles/install.zuo
Unless configured with `--installabsolute`, install "scheme", "petite", and "scheme-script" as soft links to executables in the library directory that contains boot files. That way, multiple versions can be installed easily by referencing executables inthe library directory.
Configuring with `--installabsolute`, which already restored the old boot search-path default, also restores the old installation behavior.
>  change default install of bin files to be soft links to lib files

- configure
The `+=` argument form provides a way of extending the current or default value of a compiler-configuration variable, instead of replacing it (which is something that I've often wanted). For example, `CFLAGS+=-std=gnu99` adds `-std=gnu99` to the C compiler flags, instead of requiring `CFLAGS="-O2 -std=gnu99"` to keep the default and add a new flag.
Besides providing a way to extend the default flags, `+=` provides a way to add multiple flags in a set of `configure` arguments where spaces always separate the `configure` arguments and not flags (as long as the flags themselves do not have spaces). Using `+=` that way helps avoid trouble when passing a set of configure arguments through YAML, environment variables, and shell scripts.
> add `CFLAGS+=...` handling to `configure`

- .github/workflows/ci.yml
- c/foreign.c
- c/self-exe.c
C99/GNU99 is obviously well established and a sensible choice of standard for a C code base. Still, in some environments where it remains useful to compile Chez Scheme, the default `gcc` mode is GNU89.
Since C isn't the main development language for Chez Scheme, since it's easy to stick to GNU89, and since that usefully reduces build friction, this commit makes the few changes needs to get back to GNU89. GitHub CI is configured to use `-std=gnu89` for two builds to help maintain the choice.
GNU89 is a little more flexible than C89 (ANSI C), because it allows declarations in the middle of a block, but it does not allow variables defined in the parentheses after `for`. We also rely on GNU extensions for inlining declarations.
The CI configuration here relies on #781, so this PR is a …
> Use GNU89 for kernel C

- mats/5_6.ms
- s/5_6.ss
The old `$vector-copy!` could use `$ptr-copy!`, which doesn't have an associated write barrier. As a result, using `$vector-copy!` at the end of `vector-sort!` is incorrect.
The new test is arranges for one half of a vector to have generation-0 objects and the other to have immediate objects; the two halves are already sorted, so they end up being swapped via a temporary vector and `$vector-copy!`. As a result, a collection afterward can fail to scan the half of the original vector that it should scan.
The solution here is to rename the internal `$vector-copy!` function to `$vector-fill-copy!` (by analogy to `$stencil-vector-fill-set!`) and use keep using it for things like `vector-copy`. But the new `$vector-copy!` as used by `vector-sort!` avoids `$ptr-copy!`.
> ensure write barrier in last step of `vector-sort!`

- build.zuo
In response to #791, change `make re.boot` to record success so that a subsequent `make` doesn't start over with pb. The `<m>.boot` target already worked that way, and so both targets now use the same helper.
Meanwhile, avoid building a `pb` executable if it won't be run for building platform-specific boot files.
> avoid rebuilding boot files via pb after `make re.boot`

- mats/record.ms
- s/cp0.ss
A follow-up to c081296367, this commit adjusts the cp0 change to prefer an existing case instead of the new one. This order still passes the new test, it passes old ones with a small adjustment, and it passes Racket tests that are similar to "cp0.ms" tests.
> cp0: combine dropping a binding and `begin` rotation

- csug/debug.stex
Updated broken URL to point to the Scheme.com copy of Kent Dybvig's "How to Debug Chez Scheme Programs".
Also, I think I found a copy/paste error in the file:
```
Box inspector objects. Box inspector objects contain Chez Scheme boxes.
...
TLC inspector objects. Box inspector objects contain Chez Scheme boxes.
```
I suspect the description of TLC inspector objects is a copy/paste error from the description of Box inspector objects.  I'm not sure what an accurate and useful description of a `TLC inspector object` is, though.  If anyone knows, please fix!  :)
> Update debug.stex to fix link to "How to Debug Chez Scheme Programs".

- csug/numeric.stex
According to the code of `S_random_state_next_double` at https://github.com/cisco/ChezScheme/blob/1f5adec2c18712c89eb1692458fcf5d6514bff42/c/random.c#L108-L109 (which is invoked by `pseudo-random-generator-next!`), the value is in the range (inclusively) 1 / (m1 + 1) to m1 / (m1 + 1). Therefore, 0.0 cannot be the result.
> doc: pseudo-random-generator-next! can't return 0.0

- .github/workflows/ci.yml
- c/prim5.c
- c/version.h
- mats/io.ms
Intended to address #797.
History note: the iconv library in macOS 14.0 was especially broken. By 14.2.1, it has been mostly fixed, but I think the Chez Scheme test suite uncovers a remaining problem. That problem persists in 14.3.1. 
The two different failing cases have different reasons:
* The test at line 1004 fails because iconv encodes a BOM to UTF-8 as 0 bytes. That's arguably correct behavior (a BOM encoding isn't supposed to appear in UTF-8), and the test suite can accommodate it by just avoiding a BOM.
* The test at line 710 fails due to behavior that seems to be a lingering bug in iconv, where the library incorrectly reports too little decoding success (by not advancing the output pointer) than it should when failing to convert a lambda character to a Chinese encoding. The …
> adjustment and workaround for macOS iconv

- BUILDING
- build.zuo
- configure
- makefiles/Makefile.in
This patch series repairs and improves support for configuring Chez Scheme to use external copies of some dependencies normally included as submodules. Overall, these changes let Chez Scheme be built in ways that already worked to build older versions of Chez Scheme and the copy of Chez Scheme distributed with Racket (because the configure script in the Racket sources tried less hard to make sure the dependencies were really present).
1. The first patch fixes the checks for the `zlib` and `lz4` submodules, which are currently noops, to actually perform checks unless configured with `ZLIB=<zlib>` or `LZ4=<lz4>`, respectively.
2. The second patch adds an analogous `ZUO=<zuo>` argument. Rather than simply skip the submodule check and require the user then to build with `make ZUO=zuo` (or to …
> Repairs and improvements for building with external dependencies

- c/globals.h
- c/schsig.c
- c/thread.c
- csug/system.stex
This change is an attempt to address #809.
My guess here is that the test crashes when signal 14 is delivered to a thread that is not a Scheme thread. In particular, if a GC has happened previously while multiple threads were running, then GC worker threads may be waiting around. They haven't masked signals, and the thread-local variable for a thread context will be NULL in those worker threads.
In that scenario, I don't think the signal would get delivered to a non-main thread on macOS, because `sigprocmask` and the automatic masking of signals during delivery is process-wide there. On Linux, however, the signal mask is thread-specific. That difference would explain why I see the crash rarely and (in retrospect, as far as I can remember) only when trying out different Linux systems and …
> constrain signal delivery to Scheme to the main thread

- c/version.h
This configuration enables pb mode to run on s390x.
See also to racket/racket#4951.
> add configuration for s390x (and related) to `c/version.h`

- csug/system.stex
> Fix a typo in CSUG.

- configure
- makefiles/Makefile.in
Continuing from b8838c3280, adjust the generated makefile so the supplied <command> is not a makefile dependency. That way, `ZUO=zuo` works if `zuo` is installed and the current build directory is not the source directory. (The `zuo` executable is a dependency in a real and relevant sense, but not in the sense of dependencies that we normally track in makefiles.)
Also adapt the makefile for the case that `ZUO=...` is not supplied and the build directory is not the source directory, in which case `ZUO_LIB_PATH` needs to be relative to the source directory.
Using `make ZUO=zuo` can also work, but in that case, `bin/zuo` is still built as a dependency. It's possible that some portable makefile magic could overcome that limitation, but it doesn't seem important.
CC: @LiberalArtist
> adjust `configure ZUO=<command>` support

- c/prim5.c
The availability of the iconv procedure varies with different build settings, so I believe the ICONV macro should be used here instead. With this change in place, I'm able to get PB Racket CS running on iOS.
> replace call to iconv procedure with ICONV macro

- c/atomic.h
This change makes a `tpb32l` build work for ARM before ARMv6 — including the `armel` Debian build, as opposed to `armhf`.
The main obstacle to supporting older Arm processors directly is that the "arm32.ss" backend currently uses hardware-supported floating point instructions via the VFP extension, which means ARMv6 and later. A software floating-point mode could be added (or restored, since it looks like there may have been one at some point?), but my guess is that there isn't any demand at the moment. Meanwhile, this simple change at least lets `tpb32l` build. 
See also racket/racket#4955.
> avoid wrong assembly code for threaded mode on ARMv5 and earlier

- s/pbchunk.ss
C code generated by the pbchunk conversion is especially verbose, with long macro names for simple operations and lots of comments to reflect source instructions. Generation of that code was formerly rendering to text in memory, and then splitting into the output files, which turns out to use a lot of memory. Converting to text at the last minute can have a much lower peak memory use.
If memory is at a premimum, then rendering to a temporary file would work even better, but this change already brings memory use in line with other build actions without having to deal with a temporary file. Memory use could also be reduced by dropping comments that connect to source instructions; again, though, doesn't seem necessary for now.
Related to racket/racket#4955.
> reduce memory use of pbchunk conversion

- boot/pb/gc-ocd.inc
- boot/pb/gc-oce.inc
- boot/pb/gc-par.inc
- mats/foreign.ms
- release_notes/release_notes.stex
- s/mkgc.ss
A reference bytevector is intended to be used as a multiple of a word size, but there's no explicit constraint, and so it should work with any length. When the length is not a multiple of the word size, then in a copying step, extra bytes at the end of the bytevector were missed.
The bug was exposed on a 32-bit platform by tests added as part of #821.
> repair GC for reference bytevector whose length isn't a multiple of a word

- IMPLEMENTATION.md
- c/ffi.c
- mats/ftype.ms
- s/pb.ss
- s/prims.ss
Support via libffi for pb32 had not been well tested before. Just running existing tests turned up several problems in the handling of callable addresses and 64-bit arguments and results.
To run tests, I used a 32-bit x86 machine, but it turns out that pb32l is not completely compatible with non-Windows 32-bit x86, because pb32 assumes 8-byte alignment in structures for `double`s and `int64`s. If we wanted to better support pb32 builds on x86, then probably there should be a new machine variant alongside pb32l. I don't see any real use for that, though, since 32-bit x86 machine code is supported directly. (For testing, I just hacked the alignment in a pb32l build by changing `pbcommon.def`.)
> repairs for pb32 foreign interface

- c/atomic.h
- c/build.zuo
- c/pb.c
- c/pb.h
- c/schsig.c
- c/types.h
- mats/build.zuo
CAS variants with different fence properties in "atomic.h" ware a leftover from an early experiment in parallel garbage collection, and that experiment did not turn out to be a good idea. The CAS variants were left half-implemented, and they're not needed, so this commit simplifies to reflect the needed functionality. Also, the commit adds comments to clarify that CAS support is used only for pb mode and to explain trade-offs for inline assembly and compiler intrinsics.
Small repairs to the build scripts enable pbarch builds on Windows, for what it's worth. Otherwise, this is just an internal clean-up and does not add anything new or fix any bugs.
> clean up memory fence and compare-and-swap kernel functions

- BUILDING
- c/build.zuo
- configure
A follow-up to #828 
When building an pb variant like `tpb64l`, and even when building for a platform without native-code support, the "configure" script may still be able to infer suitable C compilation and linking flags for the kernel. For example, configuring with just `-m=tpb64l` on ppc64l Linux should pick up good compiler and linker flags.
An `--os=...` flag can override inference in "configure" in case it's not correct, which might be needed for cross compilation of pb variants.
With these changes, `-m=pb` by itself is now equivalent to `--pb`, instead of triggering an error to say that `--pb` must be used. Using `-m=pb` is not equivalent to `--pb` in all cases, since `--pb --threads` is like `-m=tpb`, but `-m=pb --threads` would be an error due to the mismatch between an explicit …
> configure: improve inference of compiler flags for pb builds

- mats/5_3.ms
- release_notes/release_notes.stex
- s/5_3.ss
For an argument exact integer greater than 4294967087, generation of a random integer by piecing together smaller random numbers was broken. It didn't cover the whole range uniformly, and by mistreating the largest part of the integer, it could always produce 0 (e.g., for `(expt 2 32)`).
Closes #830
> repair `pseudo-random-generator-next!` for large integers

- csug/system.stex
- mats/cptypes.ms
- release_notes/release_notes.stex
- s/cp0.ss
- s/cptypes.ss
When `debug-level` is 2 or more, optimization is supposed to refrain from moving a call to an error function into tail position of the enclosing function. (That's a stronger guarantee than the usual one of not moving an expression into tail position if there's potentially a way to detect the movement through continuation marks.) An earlier commit 6a73b9edc7 strengthened movement of error calls in a way that did not preserve this `(debug-level 2)` constraint, so this commit primarily adjusts those changes. Also, the earlier commit 19af32e2d allowed the compiler to move an error call out of tail position, and that transformation is now suppressed when `debug-level` is 2 or more.
These changes are meant to help with debugging, but they're not enough to implement the previously specified …
> restore `(debug-level 2)` behavior, but reduce its guarantees

- c/expeditor.c
- c/prim5.c
- c/version.h
~~Accompanies the same changes in the racket repo https://github.com/racket/racket/pull/5004~~
This was originally a patch just to get racket to build on cosmopolitan libc, which unfortunately would require more heavy lifting in the main distribution to work. I took what I had there and made it so that at least Chez will work more or less as advertised, a single binary that can hit many common operating systems on amd64 and aarch64, with no installation required.
See the cosmopolitan project page for more information https://github.com/jart/cosmopolitan
> Allow building against cosmopolitan libc

- c/atomic.h
- c/pb.h
- c/version.h
As recommended in #845, use `__has_builtin` when available.
> use `__has_builtin` to detect available intrinsics

- BUILDING
- build.zuo
- configure
- makefiles/Makefile-cross.in
- makefiles/Makefile.in
- makefiles/install.zuo
Add a `--cross` argument to `configure` to indicate that the generated makefile's `make` should be like `make kernel`, and a pb-based bootstrap should rerun `configure` to build for the host machine instead of the specified target machine.
Also, add support for `DESTDIR` as a more conventional alternative to the `--temproot` configure flag. While we're at it, recognize `CFLAGS_FOR_BUILD` for building `bin/zuo`.
As part of the change to `configure`, having `CC_FOR_BUILD` set does not by itself disable the use of pb for creating or updating boot files. Depending on how boot files are obtained, `--force` now may be needed when using `CC_FOR_BUILD` as part of a cross compile that doesn't use `--cross`.
Relevant to #847 and #848
> improve cross-compile instructions and makefile support

- scheme.1.in
Manpages have a standard format for the line that is used by the `whatis` command and lintian was complaining that Chez's pages did not use the right format. This commit fixes those lines.
> fix the whatis lines in scheme.1.in

- c/version.h
Building on the s390x, m68k and hppa architectures using bytecode does not work. The build fails with `illegal pb instruction` or `invalid memory reference` while running bytecode. This commit fixes that by amending an architecture list that lists big endian architectures.
> fix bytecode endianness handling on s390x, m68k and hppa

- c/expeditor.c
Building on Debian GNU/Hurd i386 fails because of an implicit declaration of `wcwidth`. This commit makes GNU/Hurd use the same declaration that is used on GNU/Linux.
> fix missing `wcwidth` declaration on GNU Hurd

- configure
Most Linux systems have the `getconf` and `lscpu` programs that allow us to automatically detect the system's endianness. This commit uses those commands to set the default bytecode endianness and machine word size.
> configure: automatically detect endianness and word size on Linux

- mats/patch-compile-0-t-f-f
- mats/root-experr-compile-0-f-f-f
- s/5_3.ss
- s/library.ss
Functions like `vector-ref`, `string-ref`, `substring`, and `bitwise-bit-field` report a non-exact-integer index as a "bad index" error. But `bitwise-bit-set?`, `logbit?`, `logbit0`, and `logbit1` said "not an exact integer", instead, while reporting "bad index" for a negative exact integer; `bitwise-copy-bit` said "not a nonnegative exact integer". This commit changes the error message for those last five functions to always say "bad index".
Fixnum variants of the operations can still say "not a fixnum" or "invalid bit index", depending on whether the index is a negative fixnum. That seems justified on the grounds that fixnum operations add an extra constraint on their arguments. Another possible direction is to change the error messages to consistently "not a nonnegative exact integer" …
> small error-message consistency improvement for bit indices

- mats/build.zuo
- mats/foreign3.c
- mats/ftype.h
For some build environments, `_WIN32` is needed (as in other "foreign*.c" files) instead of `WIN32` without the leading underscore.
> fix foreign test for i3nt

- s/strip.ss
This is an internal function, but it's used by a decompilation tool that's included with Racket: `raco decompile --partial-fasl`.
> repair check in `$describe-fasl-from-port`

- makefiles/boot.zuo
The main submodule hasn't worked since at least commit 10d59cc, and documented build modes have been added in the mean time that support its former uses.
Closes https://github.com/cisco/ChezScheme/issues/810
----
(The change to Guix to stop using `boot.zuo` directly has been live since April.)
> makefiles/boot.zuo: remove broken main submodule

- mats/root-experr-compile-0-f-f-f
- s/read.ss
```
Chez Scheme Version 10.0.0
Copyright 1984-2024 Cisco Systems, Inc.
> #vfl(1)
Exception in read: non-fixnum found in flvector
```
> "non-fixnum found in flvector" => "non-flonum found in flvector"

- mats/cptypes.ms
- s/cptypes-lattice.ss
- s/cptypes.ss
Move `list` form the normalptr slot to the multiplet slot. In particular, this allows the reduction of
```
(lambda (x f)
(unless (list-assuming-immutable? x)
(f)
(list-assuming-immutable? x)))
```
`pair`s are split in `list-pairs` and `nonlist-pairs`. A `pair` may go from one classification to the other, so the internal representations of the `list?` predicate use both of them or neither.
> improve support for lists in cptypes

- mats/8.ms
- release_notes/release_notes.stex
- s/syntax.ss
This fixes issue #861.
The mistake was an incorrect application of a wrap.
> fix incorrect wrapping in quote-syntax

- mats/cp0.ms
- release_notes/release_notes.stex
- s/cp0.ss
- s/primdata.ss
Implements the suggestion in #872
In cp0, replace `(call/cc (lambda (k) body))` with just `body` when `k` is not referenced in `body`.
> optimize `(call/cc (lambda (k) body))` with unused `k`

- mats/misc.ms
- mats/patch-compile-0-t-f-f
- mats/root-experr-compile-0-f-f-f
- release_notes/release_notes.stex
- s/syntax.ss
Repair for #871 
Include non-`r6rs:`-prefixed names in those environments.
> repair `(scheme-report-environment 5)` and `(ieee-environment)`

- c/gc.c
- c/version.h
- mats/thread.ms
- s/mkgc.ss
This patch avoids a miscompile using Clang v15 on macOS. The default compiler on macOS was recently upgraded to Clang v16, which appears to fix the problem, and I have not been able to replicate the problem with Clang v15 variants that are available in Linux distributions. So, it might be ok to just ignore the problem. But since v15 installations are likely to hang around for a while in other macOS installations, since the workaround is simple, since Racket users who build themselves are affected, and since I spent *a lot* of time tracking down the problem, I'm inclined to include a workaround.
For details on the miscompile at it affects Chez Scheme, see [clang15-miscompile.zip](https://github.com/user-attachments/files/17355942/clang15-miscompile.zip).
> workaround Clang v15 AArch64 miscompile that affects parallel collection

- .github/workflows/ci.yml
- .github/workflows/summarytest-more
- c/version.h
- mats/thread.ms
Repair the test so that it works when the maximum collect generation is set to 1, and add a `test-more` case to the CI configuration.
Also, refine a workaround preprocessor check to enable it only when `defined(__apple_build_version__)`.
> repair thread test for `make test-more`

- boot/pb/scheme.h
- c/schlib.c
- csug/foreign.stex
- release_notes/release_notes.stex
- s/mkheader.ss
The header file scheme.h defines `Smake_flvector`, but Chez Scheme does not provide an implementation. C code can use the header, but calling `Smake_flvector` results in an error trying to reference an undefined symbol.
> Add missing Smake_flvector implementation

- mats/4.ms
- release_notes/release_notes.stex
- s/syntax.ss
The expansion of `with-continuation-mark` positioned the key and value expressions outside of the current continuation marks, which meant that attempting to look up a continuation mark in the key or value expression would fail.
This is a repair for #885.
> repair `with-continuation-mark` when accessing marks in key or value

- c/expeditor.c
The `ee_` functions are internal support for expeditor, but Racket puts them to good use for a customized expeditor. This commit adds a small new function to expose the internal `winched` flag. That flag is normally accessed via `ee_read_char`, but calling `ee_read_char` commits to reading a character, while the new function can be used to just check whether input is ready (in combination with checking the input file descriptor).
> expose expeditor SIGWINCH state via `ee_pending_winch`

- mats/fx.ms
- release_notes/release_notes.stex
- s/base-lang.ss
- s/cp0.ss
- s/cpprim.ss
- s/np-help.ss
- s/target-fixnum.ss
At optimize-level 3, cp0 can replace calls to `fxdiv-and-mod`, where the second argument is constant, with calls to `fxdiv` and `fxmod` that the back-end does not inline (when the constant is not a power of two). This aims to address issue #892 by helping cp0 anticipate how the back-end will handle the transformed code.
> anticipate back-end when inlining fxdiv-and-mod

- csug/numeric.stex
- mats/fx.ms
- release_notes/release_notes.stex
- s/cpprim.ss
- s/mathprims.ss
- s/primdata.ss
The `fx-/wraparound` function was treated like R6RS `fx-` by cp0, which meant that it could reduce a 2-argument call with `0` as the first argument to a 1-argument call, even though `fx-/wraparound` was defined with only a 2-argument form. Making `fx-/wraparound` more like R6RS `fx-` seems like the path of least resistance and least likelihood of future bugs.
> repair `fx-/wraparound` with `0` first argument, allow one argument

- s/7.ss
- s/exceptions.ss
Chez Scheme 10's new call-in-continuation procedure allows implementing guard in a simpler and likely more efficient way.
> Simplify guard form using call-in-continuation

- c/build.zuo
- c/mingw.zuo
- c/prim5.c
- release_notes/release_notes.stex
The MinGW C library's implementations of `pow`, `sin`, and `cos` have precision issues on i386 and amd64. The MSVCRT and UCRT implementations are good (I think the MSVCRT ones may have been worse 10-15 years ago), and the build links to those, anyway, so adjust linking to use `pow`, `sin`, and `cos`  from MSVCRT/UCRT when building with MinGW. There's no issue with AArch64.
Thanks to @bdeket for tracking down these issues.
Background: https://github.com/racket/racket/issues/5191, https://github.com/racket/racket/pull/5211
> building with MinGW: link to MSVCRT/UCRT for `pow`, `sin`, and `cos`

- csug/objects.stex
> Fix typo in string-copy! documentation

- BUILDING
- c/clearcache.c
- c/version.h
Recent versions of the build tools on macOS define `TARGET_OS_IPHONE` as 0 when not compiling for iOS.
Closes #896 and #928
> change `TARGET_OS_IPHONE` preprocessor handling

- c/main.c
- csug/use.stex
- release_notes/release_notes.stex
- scheme.1.in
A CLI flag isn't very convenient for modifying history file locations, since it needs to be specified in many contexts, some of which are difficult to actually modify the argument list for.
It's common practice (less, node, psql, python, sqlite… the list goes on) to allow setting the history file location from an environment variable named something like `PROJECT_HISTORY`.
When set, it overrides the default when nothing else is specified, but is still overriden by a CLI argument.
This implements this feature in Chez.
I haven't tested this yet (I might get to it somewhat later), and I'm relatively unfamiliar with sTeX (changes to which I also haven't tested so far). I figured I would open this "early" to allow for any relevant comments to be made in the interim, though I don't expect this …
> Allow setting history file location from environment

- c/prim5.c
- mats/5_3.ms
- mats/mat.ss
- release_notes/release_notes.stex
- s/5_3.ss
Advice and implementation provided by @gambiteer via racket/racket#5228.
I'm not sure about my approach to testing here. In principle, `expt` should produce a accurate result, but the result relies on `pow` from the C library, and the quality of that function varies. On GitHub CI, even `a6osx` doesn't produce a accurate result, even though it does on machines that I have access to — at least, I get a precise result with the changes in `prim5.c`. Overall, maybe there is a better approach.
> improve `expt` on a flonum to a large exact power

- c/prim5.c
- mats/5_3.ms
Despite helpful reviews, I managed to mangle part of #950.
An intended change was to use `pow` instead of `powl` for x86_64 and AArch64 macOS. The mangled change caused `powl` to be used even more broadly, instead. Also, simplify the comment, since extra caveats seem related to experiments with a similarly incorrect change, and adjust the test, since results on x86_64 macOS should be reliably accurate.
Noticed by @gambiteer by the time it was merged to Racket: https://github.com/racket/racket/commit/de67e3372038316b956b958d1f9864a406d20d01#r161150380
> correct `powl` that was intended to be `pow`

- c/clearcache.c
When I was compiling ChezScheme for RISC-V and Loongarch, I encountered an issue
```
[  361s] ChezScheme/c/clearcache.c:48:3: error: call to undeclared function '__clear_cache';  ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
[  361s]    48 |   __clear_cache((char *)start, (char *)end);
[  361s]       |   ^
[  361s] 1 error generated.
```
This issue is due to the fact that implicit function declarations are not allowed after ISO C99, so I fixed it.
> Fix undeclared __clear_cache.

- s/5_3.ss
This change will have no affect on the machine code generated for `flbit-field`, normally, since `fx-` and `fx-/wraparound` produce the same code in unsafe mode, as do `fxsll` and `fxsll/wraparound`. But this repair avoids failure in "fl.ms" afer compiling Chez Scheme itself in safe mode with something like `zuo . o=0`.
Another possibility is to allow only a smaller bit width (by 1 bit) to reach the relevant expression. Using wraparound operators seems more conservative in that it keeps the generated code the same.
> wraparound fixnum operations in the implementation of `flbit-field`

- c/externs.h
- c/new-io.c
- c/prim5.c
- s/7.ss
- s/io.ss
- s/primdata.ss
Based on the approach by @rmolives in #966. The difference here is more specific checking for `ESPIPE` to make sure that the reason `lseek` failed is that a device does not support seeking.
Seeking is used by `do-load` for three reasons: to check for a starting `#!` line to treat as a comment, to check whether the input is a compiled file, and to create a source-file description to be used later (if possible) to convert positions to lines and columns. The last of those really expects a regular file, so it could be avoiding when seeking is not supported, and the other two could be handled by generalizing peeking/ungetting for a small, bounded number of characters. But probably reading everything into a bytevector before parsing is good enough for this small corner.
> allowing loading from input paths that do not support seeking

- csug/objects.stex
There are three typos in flvector examples, which seem to be an artefact of duplicating the section on fxvectors.
> Fix typo in flvector examples
